name = "BitSetTuples"
uuid = "0f2f92aa-23a3-4d05-b791-88071d064721"
authors = ["Wouter Nuijten"]
version = "1.0.0-DEV"

[deps]
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
